spring.application.name=backend

# Render provides PORT.
# Locally, it will use 8080.
server.port=${PORT:8080}

# Gemini
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.temperature=0.5
GEMINI_API_KEY = your actual Gemini key